server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
aws:
  region: "us-west-2"

token:
  age:
    refresh: 2592000
    access: 10800

---
spring:
  profiles: local

server:
  port: 8087

dynamodb:
#  accounts: "archipelago-local.accounts"
#  account-mapping: "archipelago-local.account-mapping"
#  accounts-git: "archipelago-local.accounts-git"
  auth-codes: "archipelago-local.auth-codes"
  auth-users: "archipelago-local.auth-users"
  auth-clients: "archipelago-local.auth-clients"
  auth-jwks: "archipelago-local.auth-jwks"

auth:
  url: http://localhost:8087

aws:
  access:
    id: "AKIARDAF5R4OODU52YJR"
    key: "HRG7W4XQESB1ixNknOhZ4dYRgnvAk/U3NgUOF7fH"

---
spring:
 profiles: alpha

auth:
  url: http://auth-alpha.archipelago.build

---
spring:
 profiles: beta

auth:
  url: http://auth-beta.archipelago.build

---
spring:
 profiles: prod

auth:
  url: http://auth.archipelago.build