server:
  port: ${APP_PORT:8080}
  error:
    include-stacktrace: never

aws:
  region: ${AWS_REGION:us-west-2}

token:
  age:
    refresh: 2592000
    access: 10800
    authToken: 600
    deviceCode: 600
    authCookie: 2592000

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER:https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf}

oauth:
  client-id: ${OAUTH_ID:3ad886knkeo0vuvvpnvtp6rtlq}
  client-secret: ${OAUTH_SECRET:r5qd4fhj931vvlbf2oi3dhe58kjtfk2n7i70da7kc2d08sccch5}

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8087}

dynamodb:
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"
  auth-codes: "archipelago-local.auth-codes"
  auth-users: "archipelago-local.auth-users"
  auth-clients: "archipelago-local.auth-clients"
  auth-jwks: "archipelago-local.auth-jwks"

url:
  auth-server: ${APP_URL:http://localhost:8087}
  frontend: ${FRONTEND_URL:http://localhost:3000}

aws:
  access:
    id: ${AWS_KEY:AKIARDAF5R4OODU52YJR}
    key: ${AWS_SECRET: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}

---
spring:
 profiles: alpha

auth:
  url: ${APP_URL:http://auth-alpha.archipelago.build}

---
spring:
 profiles: beta

auth:
  url: ${APP_URL:http://auth-beta.archipelago.build}

---
spring:
 profiles: prod

auth:
  url: ${APP_URL:http://auth.archipelago.build}
