server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
aws:
  region: "us-west-2"

---
spring:
  profiles: local

server:
  port: 8087

dynamodb:
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

aws:
  access:
    id: "AKIARDAF5R4OFYCLE362"
    key: "2kQ8dMOf066HoBlOkEo+Hqpd1zzgsqmO3E3qVAS7"

---
spring:
 profiles: alpha

---
spring:
 profiles: beta

---
spring:
 profiles: prod