server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
aws:
  region: "us-west-2"

---
spring:
  profiles: local

server:
  port: 8087

dynamodb:
#  accounts: "archipelago-local.accounts"
#  account-mapping: "archipelago-local.account-mapping"
#  accounts-git: "archipelago-local.accounts-git"
  auth-codes: "archipelago-local.auth-codes"
  auth-users: "archipelago-local.auth-users"
  auth-clients: "archipelago-local.auth-clients"
  auth-jwks: "archipelago-local.auth-jwks"

aws:
  access:
    id: "AKIARDAF5R4OODU52YJR"
    key: "HRG7W4XQESB1ixNknOhZ4dYRgnvAk/U3NgUOF7fH"

---
spring:
 profiles: alpha

---
spring:
 profiles: beta

---
spring:
 profiles: prod