spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4ODZ2LMPNZ"
    key: "MS7flruyxp3QPlEVEd41NZVDG7WTkkZYBfZjfWEM"

services:
  versionset:
    url: "http://localhost:8091"
  packages:
    url: "http://localhost:8090"

dynamodb:
  build: "builds.alpha"
  build-packages: "builds-packages.alpha"
  accounts: "accounts.alpha"
  account-mapping: "account-mapping.alpha"
  accounts-git: "accounts-git.alpha"
s3:
  logs: "alpha-archipelago-build-log"

sqs:
  build-queue: "https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-queue-alpha"
workspace:
  path: "/Users/kasper.sogaard/Downloads/BuildServer"

oauth:
  client-id: "49o8iok838r23u7ivmq5g106ci"
  client-secret: "19q4onmr0khqdod7ckohq362hjfs3sbtbfebp0u4ob13rugvfsqj"
