version: "3.7"
services:
  harbor-service:
    image: build.archipelago/harbor-service:latest
    environment:
      - APP_PORT=8080
      - FRONTEND_OAUTH_ISSUER=http://auth-service:8080/oauth2
      - AUTH_SERVICE_URL=http://auth-service:8080
      - PACKAGE_SERVICE_URL=http://package-service:8080
      - VERSIONSET_SERVICE_URL=http://version-set-service:8080
      - BUILD_SERVICE_API_URL=http://build-server-api:8080
      - APPLICATION_STAGE=local
    ports:
      - 8093:8080
  auth-service:
    image: build.archipelago/auth-service:latest
    environment:
      - APP_PORT=8080
      - APPLICATION_STAGE=local
    ports:
      - 8087:8080
  build-server-api:
    image: build.archipelago/build-server-api:latest
    environment:
      - APP_PORT=8080
      - PACKAGE_SERVICE_URL=http://package-service:8080
      - VERSIONSET_SERVICE_URL=http://version-set-service:8080
      - APPLICATION_STAGE=local
    ports:
      - 8095:8080
  build-server-builder:
    image: build.archipelago/build-server-builder:latest
    environment:
      - APP_PORT=8080
      - PACKAGE_SERVICE_URL=http://package-service:8080
      - VERSIONSET_SERVICE_URL=http://version-set-service:8080
      - APPLICATION_STAGE=local
      - WS_PATH=/tmp/archipelago
    ports:
      - 8096:8080
  package-service:
    image: build.archipelago/package-service:latest
    environment:
      - APP_PORT=8080
      - APPLICATION_STAGE=local
    ports:
      - 8090:8080
  version-set-service:
    image: build.archipelago/version-set-service:latest
    environment:
      - APP_PORT=8080
      - PACKAGE_SERVICE_URL=http://package-service:8080
      - APPLICATION_STAGE=local
    ports:
      - 8091:8080
