server:
  port: ${APP_PORT:8080}
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER:https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf}

oauth:
  client-id: ${OAUTH_ID:"4ok75klvst0vf15lel5sdbdoc0"}
  client-secret: ${OAUTH_SECRET:"1u7m9pa9njct19jbj51b592ci0ku151quhjo4n0pcm36h3lude91"}

aws:
  region: ${AWS_REGION:"us-west-2"}

---
spring:
  profiles: local

server:
  port: 8093

endpoints:
  package-service: ${PACKAGE_SERVICE_URL:"http://localhost:8090"}
  versionset-service: ${VERSIONSET_SERVICE_URL:"http://localhost:8091"}
  build-server-api: ${BUILD_SERVICE_URL"http://localhost:8095"}

dynamodb:
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

aws:
  access:
    id: ${AWS_KEY:"AKIARDAF5R4OFYCLE362"}
    key: ${AWS_SECRET:"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"}

---
spring:
 profiles: alpha

---
spring:
 profiles: beta

---
spring:
 profiles: prod
