server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

oauth:
  client-id: "4ok75klvst0vf15lel5sdbdoc0"
  client-secret: "1u7m9pa9njct19jbj51b592ci0ku151quhjo4n0pcm36h3lude91"

aws:
  region: "us-west-2"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8093}

frontend-oauth:
  auth-url: ${FRONTEND_OAUTH_ISSUER:http://localhost:8087/oauth2}

endpoints:
  package-service: ${PACKAGE_SERVICE_URL:http://localhost:8090}
  versionset-service: ${VERSIONSET_SERVICE_URL:http://localhost:8091}
  build-server-api: ${BUILD_SERVICE_API_URL:http://localhost:8095}
  auth-service: ${AUTH_SERVICE_URL:http://localhost:8087}

dynamodb:
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

aws:
  access:
    id: "AKIARDAF5R4OFYCLE362"
    key: "2kQ8dMOf066HoBlOkEo+Hqpd1zzgsqmO3E3qVAS7"

---
spring:
  profiles: alpha

frontend-oauth:
  auth-url: ${FRONTEND_OAUTH_ISSUER:http://auth.alpha.archipelago.build/oauth2}

endpoints:
  package-service: "https://package-service.alpha.archipelago.build"
  versionset-service: "https://version-set-service.alpha.archipelago.build"
  build-server-api: "https://build-service-api.alpha.archipelago.build"
  auth-service: "https://auth.alpha.archipelago.build"

dynamodb:
  accounts: "archipelago-alpha.accounts"
  account-mapping: "archipelago-alpha.account-mapping"
  accounts-git: "archipelago-alpha.accounts-git"

aws:
  access:
    id: "AKIARDAF5R4ONAKPHTEL"
    key: "oM/aUtyYnf7xxBJH5sMpjkPiMednz9e65/cFGyvn"

---
spring:
  profiles: beta
---
spring:
  profiles: prod
