server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf"

aws:
  region: "us-west-2"

oauth:
  client-id: "1iv0c51b2f7a2nsl0hnphthnq6"
  client-secret: "n1uv2fh8o1hf0medie0luo85ksh5hju0s0na1p3i7lv6c82h0ic"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8091}

dynamodb:
  version-sets: "archipelago-local.version-sets"
  version-sets-revisions: "archipelago-local.version-set-revisions"

aws:
  access:
    id: "AKIARDAF5R4OHE3DO6XE"
    key: "azF2nUIwaaUzbQtA3vnosfXr2agY+wMUa6UARybd"

endpoints:
  package-service: ${PACKAGE_SERVICE_URL:http://localhost:8090}

---
spring:
  profiles: alpha

dynamodb:
  version-sets: "archipelago-alpha.version-sets"
  version-sets-revisions: "archipelago-alpha.version-set-revisions"

aws:
  access:
    id: "AKIARDAF5R4OOOCV7XGB"
    key: "Sh9zk1sSeT3BmzJFGSr+XcqPeiLYZFEV2tjishrf"

endpoints:
  package-service: "http://package-service.alpha.archipelago.build"

---
spring:
  profiles: beta
---
spring:
  profiles: prod
