server:
  port: ${APP_PORT:8080}
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER:https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf}

aws:
  region: ${AWS_REGION:"us-west-2"}

oauth:
  client-id: ${OAUTH_ID:"1iv0c51b2f7a2nsl0hnphthnq6"}
  client-secret: ${OAUTH_SECRET:"n1uv2fh8o1hf0medie0luo85ksh5hju0s0na1p3i7lv6c82h0ic"}

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8091}

dynamodb:
  version-sets: "archipelago-local.version-sets"
  version-sets-revisions: "archipelago-local.version-set-revisions"

aws:
  access:
    id: ${AWS_KEY:"AKIARDAF5R4OHE3DO6XE"}
    key: ${AWS_SECRET:"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"}

endpoints:
  package-service: ${PACKAGE_SERVICE_URL:"http://localhost:8090"}

---
spring:
  profiles: alpha

---
spring:
  profiles: beta

---
spring:
  profiles: prod
