server:
  port: ${APP_PORT:8080}
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER:https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf}

oauth:
  client-id: ${OAUTH_ID:3e7d5fgp0bekt1o8k29rn6vleh}
  client-secret: ${OAUTH_SECRET:19qso7avuot68i69jl9j6d9qr49datlrrajbf4u7bq6kndmipqj6}

aws:
  region: ${AWS_REGION:us-west-2}

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8095}

aws:
  access:
    id: ${AWS_KEY:AKIARDAF5R4OLOFUKTG6}
    key: ${AWS_SECRET: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}

dynamodb:
  build: "archipelago-local.builds"
  build-packages: "archipelago-local.builds-packages"

s3:
  stage-logs: "archipelago-local-stage-log"
  packages-logs: "archipelago-local-packages-log"

sqs:
  build-queue: ${BUILD_QUEUE:https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-local-build-queue}

endpoints:
  package-service: ${PACKAGE_SERVICE_URL:http://localhost:8090}
  versionset-service: ${VERSIONSET_SERVICE_URL:http://localhost:8091}

---
spring:
  profiles: alpha

---
spring:
  profiles: beta

---
spring:
  profiles: prod
