server:
  port: 8090
  error:
    include-stacktrace: never

oauth:
  client-id: "H4L36UXifMqdt4T3pLgajGvap0oJ63HD"
  client-secret: "3YLhyrPbphWtZtD0quk-H_3sp9HoGMVdPej0DQNZXJ3_WTgYqeNTNzCe6bVGfPnO"
  audience: http://packageservice.archipelago.build

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf

s3:
  packages: "alpha-archipelago-packages"

dynamodb:
  packages: "packages.alpha"
  packages_versions: "packages-versions.alpha"
  packages_builds: "packages-builds.alpha"
  packages_builds_git: "packages-builds-git.alpha"
  accounts: "accounts.alpha"
  account-mapping: "account-mapping.alpha"
  accounts-git: "accounts-git.alpha"
aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4ODZ2LMPNZ"
    key: "MS7flruyxp3QPlEVEd41NZVDG7WTkkZYBfZjfWEM"