server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

s3:
  packages:
    name: "alpha-archipelago-packages"

dynamodb:
  packages:
    name: "packages.alpha"
  packages_versions:
    name: "packages-versions.alpha"
  packages_builds:
    name: "packages-builds.alpha"

aws:
  region: "us-west-2"
  access:
    id: ${AWS_ID}
    key: ${AWS_KEY}