server:
  port: 8080
  error:
    include-stacktrace: never

oauth:
  client-id: "H4L36UXifMqdt4T3pLgajGvap0oJ63HD"
  client-secret: "3YLhyrPbphWtZtD0quk-H_3sp9HoGMVdPej0DQNZXJ3_WTgYqeNTNzCe6bVGfPnO"
  audience: http://packageservice.archipelago.build

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1nl95fdx.us.auth0.com/
  jackson:
    mapper:
      accept_case_insensitive_properties: true

s3:
  packages:
    name: "alpha-archipelago-packages"

dynamodb:
  packages:
    name: "packages.alpha"
  packages_versions:
    name: "packages-versions.alpha"
  packages_builds:
    name: "packages-builds.alpha"
  packages_builds_git:
    name: "packages-builds-git.alpha"

aws:
  region: "us-west-2"
  access:
    id: "AKIARDAF5R4ODZ2LMPNZ"
    key: "MS7flruyxp3QPlEVEd41NZVDG7WTkkZYBfZjfWEM"