apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-service
        stage: alpha
    spec:
      containers:
        - env:
            - name: APPLICATION_STAGE
              value: alpha
          image: 075174350620.dkr.ecr.us-west-2.amazonaws.com/auth-service:20210327-1
          name: auth-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
