apiVersion: v1
kind: Service
metadata:
  name: auth-service-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: auth-service
