apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-build-server-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-server-api
      stage: alpha
  strategy: {}
  template:
    metadata:
      labels:
        app: build-server-api
        stage: alpha
    spec:
      containers:
        - env:
            - name: APPLICATION_STAGE
              value: alpha
          image: 075174350620.dkr.ecr.us-west-2.amazonaws.com/build-server-api:20210404-212405
          name: alpha-build-server-api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
