apiVersion: v1
kind: Service
metadata:
  name: build-server-api-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: build-server-api
