apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-harbor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-service
      stage: alpha
  strategy: {}
  template:
    metadata:
      labels:
        app: harbor-service
        stage: alpha
    spec:
      containers:
        - env:
            - name: APPLICATION_STAGE
              value: alpha
          image: 075174350620.dkr.ecr.us-west-2.amazonaws.com/harbor-service:20210404-212405
          name: harbor-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
