apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-package-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package-service
      stage: alpha
  strategy: {}
  template:
    metadata:
      labels:
        app: package-service
        stage: alpha
    spec:
      containers:
        - env:
            - name: APPLICATION_STAGE
              value: alpha
          image: 075174350620.dkr.ecr.us-west-2.amazonaws.com/package-service:20210327-1
          name: package-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
