apiVersion: v1
kind: Service
metadata:
  name: alpha-version-set-service-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: version-set-service
    stage: alpha
