version: '3.7'
services:
    {{service.name}}:
      image: {{service.image}}
      environment:
        - APP_PORT=8080
        - PACKAGE_SERVICE_URL=http://package-service:8080
        - VERSIONSET_SERVICE_URL=http://version-set-service:8080
        - SPRING_PROFILE=local
        - WS_PATH=/tmp/archipelago
      ports:
        - 8096:8080
