server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf"

aws:
  region: "us-west-2"

oauth:
  client-id: "H4L36UXifMqdt4T3pLgajGvap0oJ63HD"
  client-secret: "3YLhyrPbphWtZtD0quk-H_3sp9HoGMVdPej0DQNZXJ3_WTgYqeNTNzCe6bVGfPnO"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8090}

s3:
  packages: "archipelago-local-packages-artifacts"

dynamodb:
  packages: "archipelago-local.packages"
  packages_versions: "archipelago-local.packages-versions"
  packages_builds: "archipelago-local.packages-builds"
  packages_builds_git: "archipelago-local.packages-builds-git"
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

aws:
  access:
    id: "AKIARDAF5R4OIKW2KPCY"
    key: "uGIejRuxAS/05zH6B0w8+0IdQhd9bPX2lxxuvZoG"

---
spring:
  profiles: alpha

s3:
  packages: "archipelago-alpha-packages-artifacts"

dynamodb:
  packages: "archipelago-alpha.packages"
  packages_versions: "archipelago-alpha.packages-versions"
  packages_builds: "archipelago-alpha.packages-builds"
  packages_builds_git: "archipelago-alpha.packages-builds-git"
  accounts: "archipelago-alpha.accounts"
  account-mapping: "archipelago-alpha.account-mapping"
  accounts-git: "archipelago-alpha.accounts-git"

aws:
  access:
    id: "AKIARDAF5R4OB6ZKNWBR"
    key: "gLH+zY2FMjiWwhFc9KOY8myXKR2eNHNjjaoQXUMC"

---
spring:
  profiles: beta

---
spring:
  profiles: prod
