server:
  port: ${APP_PORT:8090}
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER:https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf}

aws:
  region: ${AWS_REGION":us-west-2"}

oauth:
  client-id: ${OAUTH_ID:"H4L36UXifMqdt4T3pLgajGvap0oJ63HD"}
  client-secret: ${OAUTH_SECRET:"3YLhyrPbphWtZtD0quk-H_3sp9HoGMVdPej0DQNZXJ3_WTgYqeNTNzCe6bVGfPnO"}

---
spring:
  profiles: local

s3:
  packages: "archipelago-local-packages-artifacts"

dynamodb:
  packages: "archipelago-local.packages"
  packages_versions: "archipelago-local.packages-versions"
  packages_builds: "archipelago-local.packages-builds"
  packages_builds_git: "archipelago-local.packages-builds-git"
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

aws:
  access:
    id: ${AWS_KEY:"AKIARDAF5R4OIKW2KPCY"}
    key: ${AWS_SECRET:"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"}

---
spring:
  profiles: alpha

---
spring:
  profiles: beta

---
spring:
  profiles: prod
