version: '3.7'
services:
    {{service.name}}:
      image: {{service.image}}
      environment:
        - APP_PORT=8080
        - FRONTEND_OAUTH_ISSUER=http://auth-service:8080/oauth2
        - AUTH_SERVICE_URL=http://auth-service:8080
        - PACKAGE_SERVICE_URL=http://package-service:8080
        - VERSIONSET_SERVICE_URL=http://version-set-service:8080
        - BUILD_SERVICE_API_URL=http://build-server-api:8080
        - SPRING_PROFILE=local
      ports:
        - 8093:8080
