server:
  port: 8093
  error:
    include-stacktrace: never

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf

endpoints:
  package-service: "http://localhost:8090"
  versionset-service: "http://localhost:8091"

oauth:
  client-id: "iijvIrTcYH7CTeBAAA1tycFKjvFvQ7n3"
  client-secret: "Kvdi9nLapjGVQ4Zt84gVKRNIA0c6Dm7xUpZNNPnCLHaiC-3Cre0tYPizTUX6G7Mf"
  audience: "http://harbor.archipelago.build"