server:
  port: 8080
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

oauth:
  client-id: "49o8iok838r23u7ivmq5g106ci"
  client-secret: "19q4onmr0khqdod7ckohq362hjfs3sbtbfebp0u4ob13rugvfsqj"

aws:
  region: "us-west-2"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8096}

aws:
  access:
    id: "AKIARDAF5R4OILLLRKQO"
    key: "IlyL5Mcj/Lp8jkl+0oss8Mx9dp5BtcwqJWpzqiWx"

services:
  packages: ${PACKAGE_SERVICE_URL:http://localhost:8090}
  versionset: ${VERSIONSET_SERVICE_URL:http://localhost:8091}

dynamodb:
  build: "archipelago-local.builds"
  build-packages: "archipelago-local.builds-packages"
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

s3:
  stage-logs: "archipelago-local-stage-log"
  packages-logs: "archipelago-local-packages-log"

sqs:
  build-queue: "https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-local-build-queue"

workspace:
  path: ${WS_PATH:C:\Users\accou\Downloads\BuildServer}

---
spring:
  profiles: alpha

aws:
  access:
    id: "AKIARDAF5R4OGUAX2HEK"
    key: "7aeDgB9cn9kqRwdv9zVQFKop591BqE7SNFDoiua7"

services:
  versionset: "https://version-set-service.alpha.archipelago.build"
  packages: "https://package-service.alpha.archipelago.build"

dynamodb:
  build: "archipelago-local.builds"
  build-packages: "archipelago-local.builds-packages"
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

s3:
  stage-logs: "archipelago-local-stage-log"
  packages-logs: "archipelago-local-packages-log"

sqs:
  build-queue: "https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-alpha-build-queue"

workspace:
  path: ${WS_PATH:/tmp/archipelago}

---
spring:
  profiles: beta

---
spring:
  profiles: prod
