server:
  port: 8080
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

oauth:
  client-id: "49o8iok838r23u7ivmq5g106ci"
  client-secret: "19q4onmr0khqdod7ckohq362hjfs3sbtbfebp0u4ob13rugvfsqj"

aws:
  region: "us-west-2"

discord:
  token: "ODI3OTczMTMxOTcyOTAyOTMy.YGi0EQ.6ElImP2skqmR4d0-ie90iKbqs6c"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8096}

discord:
  channel: "827977094918307881"
  webhook: "https://discordapp.com/api/webhooks/827991379753435156/7Hf85wnYuL8CObeT16CVWmM87JbxTU6gvTyMidu94qwWYCh5ui-_JcZwDrQLTxxZo6Oh"

aws:
  access:
    id: "AKIARDAF5R4OILLLRKQO"
    key: "IlyL5Mcj/Lp8jkl+0oss8Mx9dp5BtcwqJWpzqiWx"

services:
  packages: ${PACKAGE_SERVICE_URL:http://localhost:8090}
  versionset: ${VERSIONSET_SERVICE_URL:http://localhost:8091}

dynamodb:
  build: "archipelago-local.builds"
  build-packages: "archipelago-local.builds-packages"
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.account-mapping"
  accounts-git: "archipelago-local.accounts-git"

s3:
  stage-logs: "archipelago-local-stage-log"
  packages-logs: "archipelago-local-packages-log"

sqs:
  build-queue: "https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-local-build-queue"

workspace:
  path: ${WS_PATH:C:\Users\accou\Downloads\BuildServer}

---
spring:
  profiles: alpha

discord:
  channel: "827972887125295114"
  webhook: "https://discordapp.com/api/webhooks/827993375507480597/1EO70YGv5lEi8EB5lhwP1wMOc7m5ielOtMIXGX7Tm71qYsME4Oijl3srnRY-nWrBs5PF"

aws:
  access:
    id: "AKIARDAF5R4OBNCQ7KLT"
    key: "PD45gn4xxyBcxJg4nZlQ517Y/Xaugml0SDIF7EXR"

services:
  versionset: "http://version-set-service.alpha.archipelago.build"
  packages: "http://package-service.alpha.archipelago.build"

dynamodb:
  build: "archipelago-alpha.builds"
  build-packages: "archipelago-alpha.builds-packages"
  accounts: "archipelago-alpha.accounts"
  account-mapping: "archipelago-alpha.account-mapping"
  accounts-git: "archipelago-alpha.accounts-git"

s3:
  stage-logs: "archipelago-alpha-stage-log"
  packages-logs: "archipelago-alpha-packages-log"

sqs:
  build-queue: "https://sqs.us-west-2.amazonaws.com/075174350620/archipelago-build-alpha-build-queue"

workspace:
  path: ${WS_PATH:/tmp/archipelago}

---
spring:
  profiles: beta
---
spring:
  profiles: prod
